### ISSUE TITLE
Socialite dependency is not working

### ISSUE THREAD

**Issue by pablo-bossi** [larvatecn/laravel-passport-socialite#1]
Hi,
   It seems you have recently changed dependencies and now is not allow to use this package with laravel/laravel-socialite and must use your own package instead.
    Problem is that package larva/laravel-socialite is not working as you have the abstractProvider defining an abstract method called getName which is not implemented in any of the providers (getProviderName is implemented instead)

**Comment by xutongle** [comment]
I will test and fix this issue as soon as possible。

**Comment by larvacent** [comment]
fix ok

**Comment by xutongle** [comment]
@pablo-bossi fix ok

**Comment by pablo-bossi** [comment]
Great, thanks
